### ISSUE TITLE
Pandas tables not wrapping properly

### ISSUE THREAD

**Issue by vtoliveira** [greenape/mknotebooks#24]
This is one of my first issues, I hope I am doing it right.

I tried to use mknotebooks to render a notebook, but all my pandas tables with a few extra columns are not wrapped properly.  This is a print of screen:

![image](https://user-images.githubusercontent.com/32197310/77766261-29276980-701e-11ea-907e-6fc0ae9fffb9.png)

I am not sure it this is a bug, or something that I am doing wrong, so I will label it as a question.

**Comment by LeonardAukea** [comment]
Adding this to css helps: 
```css
table {
    display: block;
    max-width: -moz-fit-content;
    max-width: fit-content;
    margin: 0 auto;
    overflow-x: auto;
    white-space: nowrap;
  }
```
